name: work

on:
  workflow_dispatch:
    inputs:
      push_changes:
        description: "Allow the workflow to commit and push generated changes"
        required: false
        default: false
        type: boolean
  schedule:
    # Syntax: https://crontab.guru
    - cron: "29 8 1-31 * *"
permissions:
  contents: write
env:
  date: ""
jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - name: Prep
        run: echo "date=$(date -u)" >> "$GITHUB_ENV"
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ">=20.10.0"
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Weekly
        if: ${{contains(env.date, 'Tue')}}
        run: |
          # This should only happen before the installation of dependencies
          find ./ -type f -name "*.ts" -exec bash -c "echo -e \"// $(date -u)\" >> {}" \;
      - name: Install dependencies
        run: |
          npm i --force
          npm update --force
          npm audit fix --force
      - name: Daily
        env:
          committer_email: ${{ vars.COMMITTER_EMAIL }}
          committer_name: ${{ vars.COMMITTER_NAME }}
        run: |
          sed -r "s/@@@/$date/" ./reamde.md > ./README.md
          sed -r "s/@@@/$date/" ./src/index.ts > ./src/index-dev.ts
          sed -r "s/@@@/$date/" ./src/app.ts > ./src/app-dev.ts
          sed -r "s/@@@/$date/" ./src/creator.ts > ./src/creator-dev.ts
      - name: Commit and push changes
        if: ${{ github.event_name == 'schedule' || inputs.push_changes }}
        env:
          committer_email: ${{ vars.COMMITTER_EMAIL }}
          committer_name: ${{ vars.COMMITTER_NAME }}
          github_token: ${{ github.token }}
        run: |
          git config --global user.email $committer_email
          git config --global user.name $committer_name
          git status
          git add README.md package.json package-lock.json src/app-dev.ts src/creator-dev.ts src/index-dev.ts
          if [[ "$date" == *Tue* ]]; then
            git add src/*.ts
          fi
          git diff --cached --quiet && exit 0
          git commit -m "Updated MS AI Bot to $date"
          git push "https://x-access-token:${github_token}@github.com/${{ github.repository }}.git" "HEAD:${{ github.ref_name }}"
